---
- name: Add Workflow Play
  hosts: all
  gather_facts: false

  tasks:
    - name: Include vars
      ansible.builtin.include_vars: ../vars/aap.yml

    - name: Create job template
      ansible.controller.job_template:
        name: "{{ job_name }}"
        job_type: "run"
        organization: "Default"
        inventory: "HashiVault Manual Host Inv"
        project: "{{ project_name }}"
        playbook: "{{ playbook_name }}"
        credentials:
          - "Hasivault SSH Cred"
          - "AnsibleVault PWD"
        state: "present"
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs:  "{{ validate_certs }}"

    - name: Create a workflow job with a pre step forced
      ansible.controller.workflow_job_template:
        controller_host: "{{ controller_host }}"
        controller_username: "{{ controller_username }}"
        controller_password: "{{ controller_password }}"
        validate_certs:  "{{ validate_certs }}"
        name: "{{ workflow_name }}"
        inventory: HashiVault Manual Host Inv
        survey_enabled: yes
        survey_spec: '{"name":"","description":"","spec":[{"question_name":"Change Number","question_description":"","required":true,"type":"text","variable":"snow_chg_no","min":0,"max":1024,"default":"","choices":"","new_question":false}]}'
        workflow_nodes:
          - identifier: WFS_SNOW_CHECK
            unified_job_template:
              organization:
                name: Default
              name: WFS_CheckChange
              type: job_template
            credentials: []
            related:
              success_nodes:
                - identifier: WFS_Cust
              failure_nodes: []
              always_nodes: []
              credentials: []
          - identifier: WFS_Cust
            all_parents_must_converge: false
            unified_job_template:
              organization:
                name: Default
              name: "{{ job_name }}"
              type: job_template
            related:
              success_nodes: []
              failure_nodes: []
              always_nodes: []
              credentials: []
      register: result    

